### ISSUE TITLE
 import _pyllamacpp as pp ImportError: initialization failed for latest versions of pyllamacpp

### ISSUE THREAD

**Issue by gidzr** [absadiki/pyllamacpp#32]
On a clean venv, installing only pip install pyllamacpp==2.4.1 or pip install pyllamacpp, 

when I run
>>> from pyllamacpp.model import Model

I get the following error:  import _pyllamacpp as pp ImportError: initialization failed

When I downgrade to pyllamacpp==2.1.3, everything works.

**Comment by absadiki** [comment]
@gidzr,
I just tested it and it's working on my side without any issue. There was no major updates between those two versions except the upgrade of `llama.cpp` submdoule, so I think the latest version of `llama.cpp` is compiled with something incompatible with your machine. 
So make sure that the version of `llama.cpp` that `pyllamacpp v2.4.1`  is pointing to (you can find it in the [releases page](https://github.com/abdeladim-s/pyllamacpp/releases)) is working properly. 
Also try to compile the package from source to generate a wheel compatible with your machine.

**Comment by gidzr** [comment]
@abdeladim-s Thanks will do!
